{"name": "test_demo1", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'", "trace": "request = <SubRequest 'adding_screenshot_Fail' for <Function test_demo1>>\n\n    @pytest.fixture()\n    def adding_screenshot_Fail(request):\n        yield\n        item = request.node\n>       if item.rep_call.failed:\nE       AttributeError: 'Function' object has no attribute 'rep_call'\n\ntest_appiumintegration.py:38: AttributeError"}, "start": 1699269917346, "stop": 1699269923934, "uuid": "8efc1e04-3403-431e-a6ce-45d5b4c7b691", "historyId": "d7e2a8866d45bab0f667cda2acfb1775", "testCaseId": "d7e2a8866d45bab0f667cda2acfb1775", "fullName": "test_appiumintegration#test_demo1", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('adding_screenshot_Fail')"}, {"name": "suite", "value": "test_appiumintegration"}, {"name": "host", "value": "DESKTOP-4U27L9N"}, {"name": "thread", "value": "5992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_appiumintegration"}]}